[build]
rustflags = [
    "-Wclippy::all",
    "-Wclippy::pedantic",
    "-Wclippy::cargo_common_metadata",
    "-Wclippy::negative_feature_names",
    "-Wclippy::redundant_feature_names",
    "-Wclippy::wildcard_dependencies",
    "-Wclippy::absolute_paths",
    "-Wclippy::allow_attributes",
    "-Wclippy::allow_attributes_without_reason",
    "-Wclippy::arithmetic_side_effects",
    "-Wclippy::as_conversions",
    "-Wclippy::as_underscore",
    "-Wclippy::assertions_on_result_states",
    "-Wclippy::clone_on_ref_ptr",
    "-Wclippy::create_dir",
    "-Wclippy::dbg_macro",
    "-Wclippy::decimal_literal_representation",
    "-Wclippy::deref_by_slicing",
    "-Wclippy::else_if_without_else",
    "-Wclippy::empty_drop",
    "-Wclippy::empty_structs_with_brackets",
    "-Wclippy::error_impl_error",
    "-Wclippy::exhaustive_enums",
    "-Wclippy::exhaustive_structs",
    "-Wclippy::exit",
    "-Wclippy::expect_used",
    "-Wclippy::filetype_is_file",
    "-Wclippy::float_cmp_const",
    "-Wclippy::fn_to_numeric_cast_any",
    "-Wclippy::format_push_string",
    "-Wclippy::get_unwrap",
    "-Wclippy::host_endian_bytes",
    "-Wclippy::big_endian_bytes",
    "-Wclippy::if_then_some_else_none",
    "-Wclippy::indexing_slicing",
    "-Wclippy::integer_division",
    "-Wclippy::large_include_file",
    "-Wclippy::let_underscore_must_use",
    "-Wclippy::let_underscore_untyped",
    "-Wclippy::little_endian_bytes",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::map_err_ignore",
    "-Wclippy::mem_forget",
    "-Wclippy::missing_docs_in_private_items",
    "-Wclippy::missing_trait_methods",
    "-Wclippy::mixed_read_write_in_expression",
    "-Wclippy::mod_module_files",
    "-Wclippy::multiple_inherent_impl",
    "-Wclippy::multiple_unsafe_ops_per_block",
    "-Wclippy::mutex_atomic",
    "-Wclippy::needless_raw_strings",
    "-Wclippy::non_ascii_literal",
    "-Wclippy::panic",
    "-Wclippy::panic_in_result_fn",
    "-Wclippy::partial_pub_fields",
    "-Wclippy::print_stderr",
    "-Wclippy::print_stdout",
    "-Wclippy::pub_without_shorthand",
    "-Wclippy::rc_buffer",
    "-Wclippy::rc_mutex",
    "-Wclippy::redundant_type_annotations",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::same_name_method",
    "-Wclippy::semicolon_inside_block",
    "-Wclippy::shadow_same",
    "-Wclippy::shadow_unrelated",
    "-Wclippy::single_char_lifetime_names",
    "-Wclippy::str_to_string",
    "-Wclippy::string_add",
    "-Wclippy::string_lit_chars_any",
    "-Wclippy::string_slice",
    "-Wclippy::string_to_string",
    "-Wclippy::suspicious_xor_used_as_pow",
    "-Wclippy::todo",
    "-Wclippy::try_err",
    "-Wclippy::undocumented_unsafe_blocks",
    "-Wclippy::unimplemented",
    "-Wclippy::unnecessary_safety_doc",
    "-Wclippy::unnecessary_self_imports",
    "-Wclippy::unneeded_field_pattern",
    "-Wclippy::unreachable",
    "-Wclippy::unseparated_literal_suffix",
    "-Wclippy::unwrap_in_result",
    "-Wclippy::unwrap_used",
    "-Wclippy::verbose_file_reads",
    "-Wclippy::wildcard_enum_match_arm",
]

[env]
# Both of these are needed to support assert_outputs!(...)
RUST_TEST_NOCAPTURE = "1"
RUST_TEST_THREADS   = "1"
