[package]
edition = "2021"
name    = "test-ur-code-xd-macro"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.67"
quote       = "1.0.33"
syn         = { version = "2.0.35", features = ["full"] }
