[package]
edition = "2021"
name    = "test-ur-code-xd"
version = "0.1.0"

[dependencies]
console               = "0.15.7"
diff                  = "0.1.13"
float-cmp             = "0.9.0"
gag                   = "1.0.0"
indent_write          = "2.2.0"
lazy_static           = "1.4.0"
num-traits            = "0.2.16"
panic-message         = "0.3.0"
regex                 = "1.9.5"
tempfile              = "3.8.0"
test-ur-code-xd-macro = { path = "../test-ur-code-xd-macro" }
thiserror             = "1.0.48"
